const mongoose = require('mongoose');

const candidateSchema = new mongoose.Schema({
  name: String,
  age: Number,
  dob: String,
  post_applied_for: String,
  height: String,
  doi: String,
  nationality: { type: String, default: "Indian" },
  weight: String,
  place_of_issue: String,
  passport: String,
  sex: String,
  status: String,
  expiry_date: String,
  passportImage: String, // path to uploaded image
  // Medical
  eye_vision_reye: String,
  eye_vision_leye: String,
  rear: String,
  lear: String,
  bp: String,
  heart: String,
  lungs: String,
  abdomen: String,
  Hydrocele: String,
  vdrl: String,
  ChestXRay: String,
  PREGNANCY_TEST: String,
  remarks: String,
  // Lab
  sugar: String,
  albumin: String,
  urine_other: String,
  Hemoglobin: Number,
  Malaria_Rapid: String,
  Microfilaria: String,
  Blood_Group: String,
  Salmonella: String,
  Bilharziasis: String,
  Helminths: String,
  V_Cholera: String,
  HBSAG: String,
  AntiHcv: String,
  HIV: String,
  Urea: Number,
  Creatinine: Number,
  BloodSugar: Number,
  Kft: String,
  lab_sr_no: String,
  fit_status: String,
  pdfPath: String,
  qrCodePath: String,
});

module.exports = mongoose.model('Candidate', candidateSchema);
